### ISSUE TITLE
RuntimeWarning: overflow encountered in multiply

### ISSUE THREAD

**Issue by dbl001** [gdetor/som_stability#2]
Are these exceptions a concern:

$ python som.py 135 0.47 0.2 04702
som.py:154: RuntimeWarning: overflow encountered in multiply
  W -= lrate * (Le.ravel() * (W - stimulus).T).T * dt
som.py:154: RuntimeWarning: invalid value encountered in subtract
  W -= lrate * (Le.ravel() * (W - stimulus).T).T * dt

Happens on Ubuntu 20.04LTS as well as OS X 10.15.7 (Catalina) with Anaconda Python 3.6.13.
```
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy
In [2]: print (numpy.__version__)
1.19.5

In [4]: import  numba

In [5]: print(numba.__version__)
0.53.1
```

**Comment by gdetor** [comment]
@dbl001 Apparently that's an issue with the parameters being used in the demo. I have updated the README file with a new set of parameters consistent with the ones provided in "Stability analysis of a neural field self-organizing map", JOMN 2020. In that paper you can find a broader set of parameters.
