### ISSUE TITLE
ValueError: cannot reshape array of size 3200 into shape (16,16,2)

### ISSUE THREAD

**Issue by dbl001** [gdetor/som_stability#3]
Any idea what's going wrong here?
Som.py line #177:
```
    plot_weights(s, w.reshape(16, 16, 2), ax, axis=[0, 1]
   ValueError: cannot reshape array of size 3200 into shape (16,16,2)
```

w's shape is 1600X2.

**Comment by gdetor** [comment]
@dbl001  Yes, the size of the neural field is n = 40 (see line 95 in som.py) which means that w has dimensions (40, 40, 2) . Then we request for a reshape of (16, 16, 2), which causes the problem. I just fixed that issue. Also create a directory named results, where the script will store all the data. After that the script should run and plot a SOM. Thank you once again for catching this.
